### PR TITLE
Fix return data for several functions

### PR DESCRIPTION
**Pull request by kenfehling**
Some functions were calling encodeId and returning only the encoded IDs while throwing away the rest of the data, but I made them return all of the data along with the encoded IDs.

### CODE REVIEW

**Comment by scheiblr** [comment]
Fixed differently in https://github.com/raphiniert-com/ra-data-postgrest/commit/690469e12aab25bd31306d82b9d42d6a1e199faf

I'm gonna release this soon.

**Comment by scheiblr** [comment]
And thank you very much for the effort! :+1:

**Comment by kenfehling** [comment]
Thanks, but it seems that your fix doesn't work exactly the same way. I think it might be because of the case where 'id' is part of a compound key. The `dataWithId` function could ignore the rest of the compound key because it contains 'id'

This part of [line 102](https://github.com/raphiniert-com/ra-data-postgrest/blob/690469e12aab25bd31306d82b9d42d6a1e199faf/src/dataProvider/index.ts#L102): `|| (data && data.id)`

**Comment by scheiblr** [comment]
Sorry @kenfehling, I never saw your response of Dec 29, 2020. It just came up in another issue and I therefore, attacked it now. v1.1.8 includes the change.

**Pull request closed without merging**
