### PR TITLE
Add support for compound primary keys

### PR DESCRIPTION
**Pull request by programmarchy**
Hello, I recently had a project where I used this data provider for react admin, but had to modify it to support tables which had primary keys which were not named `id` or even had compound primary keys. I added a parameter to the constructor that defined these types of keys:

```
const dataProvider = postgrestRestProvider(API_URL, fetchUtils.fetchJson, 'eq', new Map([
  ['course_product', 'sku'],
  ['course_vendor', ['course_id', 'vendor_id']],
]));
```

As you can see, the `course_product` table uses `sku` for its primary key, and `course_vendor` uses a combination of `course_id` and `vendor_id` e.g. `PRIMARY KEY(course_id, vendor_id)`

If there's a resource without a definition in the map, it uses the default behavior of using `id`.

I created this PR to gauge interest in merging this feature. Happy to accept criticism about the approach and improve it, also.

### CODE REVIEW

**Comment by scheiblr** [comment]
Thanks a lot, this is very interesting. I merged it for now, but one thought: for better consistency it would maybe better to always have it in the form `['table', ['id']]` even if it's only one column, what do you think?

**Comment by programmarchy** [comment]
Sounds good to me @scheiblr

**Comment by scheiblr** [comment]
Hey, just refactored your code a bit and added the change mentioned above: https://github.com/raphiniert-com/ra-data-postgrest/tree/compound-pkeys
I'm currently a bit busy. Thus, it would be nice, if you were able to test it.

**Comment by TheRealAstroboy** [comment]
Hello,

Compound primary keys support is great, but I don't understand what `getOrderBy function` is for as we can set order by code with React-Admin (with current ra-data-postgrest source code, it ignores lines of code like `sort={{ field: "name", order: "DESC" }}` ) ?

**Pull request merged**
