### PR TITLE
Rpc support

### PR DESCRIPTION
**Pull request by TheRealAstroboy**
Add support to RPC functions GET request 
(getManyReference & getList)

### CODE REVIEW

**Comment by scheiblr** [comment]
Could you please clarify the patch by an example?

**Comment by TheRealAstroboy** [comment]
I have updated the documentation in my pull request :

### Special Filter Feature (RPC Functions)
The dataProvider is designed to enable you to use Get RPC functions:

```GET /rpc/add_them?post_author=Herbert HTTP/1.1```
The function parameter names match the query parameters ```&post_author=Herbert``` if you end the field with an `@` (neither default comparator nor special comparator)

```jsx
<Filter {...props}>
  <TextInput label="Search" source="post_title" alwaysOn />
  <TextInput label="Search" source="post_author@" alwaysOn />
  // some more filters
</Filter>
```

What areas do I need to improve ?

**Comment by scheiblr** [comment]
Sorry for the late response. It was my fault and I did not really get the idea. 
Thanks for clarifying it and thank you for the very handsome contribution!
Would it be useful to exemplary give a postgres function in the example in order to give an entire picture?

**Comment by scheiblr** [comment]
Probably there should not be any backend code in this repo. I guess creating a example api and some tests would be better, which I had in my mind for long time. Maybe, this year there is the time to realize it ;)

Thanks again for your contribution!

**Pull request merged**
